server:
  port: 8080

go-push:
  zookeeper:
      servers: 192.168.99.100:32773
      listen-namespace-node-server: namespace-node-server
      listen-namespace-data-center: namespace-data-center
      session-timeout: 6000
      connection-timeout: 6000
      max-retries: 1000
      retries-sleep-time: 2000


spring:
  thymeleaf:
    cache: false

swagger:
  title: GoPush 监控中心接口
  description: ${swagger.title}文档说明
  version: ${application.version}
  license: GoPush 许可
  license-url: https://gitee.com/openWolf/gopush/blob/master/LICENSE
  terms-of-service-url: https://gitee.com/openWolf/gopush/issues/new
  contact:
    name: 喝咖啡的囊地鼠
    url: https://gitee.com/openWolf/gopush
    email: null_hello@qq.com
  base-package: com.gopush.monitor.controller
  base-path:  /**
  exclude-path: /error,/ops/**